apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-application
    env: prod
    owner: Yaroslav
spec:
  replicas: 2
  selector:
    matchLabels:
      project: mossad
  template:
    metadata:
      labels:
        project: mossad
    spec:
      containers:
        - name: mossad-web
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:                                      # ← spec не внутри metadata
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling    # ← правильное имя деплоймента
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
