apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
    env: prod
    tier: frontend
    owner: Yaroslav
spec:
  containers:
  - name: myapp-nginx
    image: nginx:latest
    ports: 
      - containerPort: 80

  - name: container-api
    image: tomcat:8.5.38
    ports: 
      - containerPort: 8080