apiVersion: v1
kind: Service
metadata:
  name: for-simple-deploy
  labels:
    owner: Yaroslav
spec:
  selector:
    project: kgb
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP